### PR TITLE
feat: Add resources

### PR DESCRIPTION
**Pull request by bantuist**
These are the resources I added @cromwellryan :

- Learn Git Branching
- Learning JavaScript Design Patterns
- Principles Wiki (for software design principles)

Here are some additional ones that we found useful, but not sure if or where to add them. 

- [Inclusive Components](https://inclusive-components.design/): from our HTML Weekly Code Review
- [The A11y Project](https://a11yproject.com/): useful articles, how-tos, and cheatsheets
- [Grid To Flex](http://www.gridtoflex.com/): flexbox fallbacks via Corinne
- [Progressive Enhancement: What It Is, And How To Use It?](https://www.smashingmagazine.com/2009/04/progressive-enhancement-what-it-is-and-how-to-use-it/): via Corinne

Also, Prettier did some auto-formatting to the markdown.

### CODE REVIEW

**Comment by cromwellryan** [comment]
Thanks @bantuist! Could I convince you to split this into the 3 (4?) logical commits you used in your commit body? The 4th in my mind is the reformatting of the sections. If you need help splitting this up, let me know.

**Comment by cromwellryan** [comment]
RE the additional ones, what about in the Addition items of phase 2?

**Comment by bantuist** [comment]
I broke up the commits.

There are a lot of resources in that document and I don't want to be adding to the noise. it feels like there should be a better distinction (perhaps linked to in another document?) between the core material to complete for the apprenticeship and the additional resources to explore as needed.

**Comment by catheraaine** [comment]
Closing this one too, re: reworking all the files!

**Pull request closed without merging**
